# Generated by Django 4.2.5 on 2023-09-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_author_alter_recipe_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='preparation_ingredients',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preparation_steps',
            field=models.TextField(blank=True, default=''),
        ),
    ]
