# Generated by Django 4.2.5 on 2023-09-18 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_preparation_ingredients_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='preparation_steps_is_html',
        ),
    ]
